<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>UnknownSurvivor</RootNamespace>
        <AssemblyName>UnknownSurvivor</AssemblyName>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="SPTushonka.Common" Version="4.1.3" />
        <PackageReference Include="SPTushonka.DI" Version="4.1.3" />
        <PackageReference Include="SPTushonka.Server.Core" Version="4.1.3" />
        <PackageReference Include="WTT-ServerCommonLib" Version="3.0.4" />
    </ItemGroup>

    <PropertyGroup>
        <TarkovDir Condition=" '$(TarkovDir)' == '' ">$(SolutionDir)..\..\</TarkovDir>
        <ServerModDir>$(TarkovDir)SPT_Runtime\user\mods\</ServerModDir>
    </PropertyGroup>

    <!-- This runs post build to copy the contents of the resource folder to a build directory -->
    <Target Name="CopyResources" AfterTargets="PostBuildEvent">
        <ItemGroup>
            <OutputDLL Include="$(ProjectDir)$(OutDir)$(TargetName).dll" />
            <Resources Include="$(ProjectDir)Resources\**\*.*" />
        </ItemGroup>

        <!-- Copy task to copy the dll and resources folder to the mods directory -->
        <Copy
                SourceFiles="@(OutputDLL);@(Resources);"
                DestinationFolder="$(ServerModDir)UnknownSurvivor\%(RecursiveDir)"
        />
    </Target>

</Project>
